### ISSUE TITLE
How do I set a breakpoint when running Vitest in browser mode?

### ISSUE THREAD

**Issue by kody-liou** [vitest-tests/browser-examples#1]
I ran pnpm install, set a breakpoint in examples/vanilla/tests/HelloWorld.spec.ts, and then executed pnpm test, but it doesn't hit the breakpoint.

![image](https://github.com/user-attachments/assets/71036575-934f-4521-bfb9-3f7ee82a2506)

My Node version: v18.17.0

My OS: macOS 14.4.1 (23E224)

My IDE: VSCode

Then I updated vitest.config.ts, but it's still not working. Below is the updated vitest.config.ts

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    browser: {
      enabled: true,
      name: 'chromium',
      provider: 'playwright',
    },
    inspect: true,
    inspectBrk: true,
    poolOptions: {
      forks: {
        singleFork: true
      }
    },
  },
  // TODO: this is to make ecosystem work, remove when fixed
  server: {
    fs: {
      strict: false,
    },
  },
})

```

**Comment by AriPerkkio** [comment]
Please use Vitest repository for issues and questions. 

See https://github.com/vitest-dev/vitest/issues/5090#issuecomment-2292867433 for related answer.
